version: '3.8'

services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/log:/var/log:ro
      - crowdsec-db:/var/lib/crowdsec/data
      - crowdsec-config:/etc/crowdsec

  exporter:
    build: ./exporter
    container_name: crowdsec-exporter
    restart: unless-stopped
    depends_on:
      - crowdsec
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=crowdmon
      - DB_PASSWORD=crowdmonpass
      - DB_NAME=crowdmondb

  db:
    image: postgres:15
    container_name: crowdmon-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: crowdmon
      POSTGRES_PASSWORD: crowdmonpass
      POSTGRES_DB: crowdmondb
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  crowdsec-db:
  crowdsec-config:
  pgdata:
  grafana-storage:
